version: '3.8'

services:
  solideng:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solideng
    ports:
      - "8000:8000" # 외부에서 접근할 수 있는 포트 설정
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - solideng
    networks:
      - app_network

networks:
  app_network:
